<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="12" total="13" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9937" started-at="2021-08-31T15:59:04Z" finished-at="2021-08-31T15:59:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9937" started-at="2021-08-31T15:59:04Z" finished-at="2021-08-31T15:59:14Z">
      <class name="Tests.HomePageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:Tests.HomePageTest@17c386de]" name="setUp" is-config="true" duration-ms="6701" started-at="2021-08-31T15:59:04Z" finished-at="2021-08-31T15:59:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyClickingOnBuyNowRedirectsUserToPopUpWindowTest()[pri:2, instance:Tests.HomePageTest@17c386de]" name="verifyClickingOnBuyNowRedirectsUserToPopUpWindowTest" duration-ms="2535" started-at="2021-08-31T15:59:11Z" finished-at="2021-08-31T15:59:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [20000] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [20000] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Tests.HomePageTest.verifyClickingOnBuyNowRedirectsUserToPopUpWindowTest(HomePageTest.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyClickingOnBuyNowRedirectsUserToPopUpWindowTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Tests.HomePageTest@17c386de]" name="tearDown" is-config="true" duration-ms="674" started-at="2021-08-31T15:59:14Z" finished-at="2021-08-31T15:59:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
